app <- ShinyDriver$new("../../", seed = 42)
app$snapshotInit("Basic_test")

app$snapshot()
app$setInputs(navbar = "2. Task")
app$snapshot()
app$setInputs(navbar = "3. Learner")
app$snapshot()
app$setInputs(navbar = "4. Train & Evaluate")
app$snapshot()
app$setInputs(navbar = "5. Benchmarking")
app$snapshot()
app$setInputs(navbar = "6. Predict")
app$snapshot()
app$snapshot()
