app <- ShinyDriver$new("../../", seed = 42, loadTimeout = 1e+05, shinyOptions = list(port = 8000))
app$snapshotInit("workflow_test_without_DT")

app$snapshot()
app$setInputs(navbar = "3. Learner")
app$setInputs(Learner_Create1 = "click")
app$setInputs(Learner1PredictTypeChoice = "prob")
app$setInputs(Learner1PredictTypeChange = "click")
app$snapshot()
app$setInputs(navbar = "4. Train & Evaluate")
app$snapshot()
app$setInputs(navbar = "5. Benchmarking")
app$setInputs(Bench_learners = "Learner1")
app$setInputs(Bench_res_strategy = "cv")
app$setInputs(Bench_start = "click")
app$snapshot()
app$setInputs(navbar = "6. Predict")
app$snapshot()
