app <- ShinyDriver$new("../", seed = 42, loadTimeout = 1e+05, shinyOptions = list(port = 8000))
app$snapshotInit("workflow_test_without_DT")

app$snapshot()
app$setInputs(navbar = "3. Learner")
app$setInputs(Learner_Create1 = "click")
app$setInputs(Learner1Paramminsplit = 10)
app$setInputs(Learner1ChangeParams = "click")
app$setInputs(Learner1PredictTypeChoice = "prob")
app$setInputs(Learner1PredictTypeChange = "click")
app$setInputs(Learner_add = "click")
app$setInputs(Learner_Learner2 = "classif.ranger")
app$setInputs(Learner_Create2 = "click")
app$snapshot()
app$setInputs(navbar = "4. Train & Evaluate")
app$setInputs(TrainFit_learner = "Learner1")
app$snapshot()
app$setInputs(TrainFit_resample = "click")
app$setInputs(Res_learner = "Learner1")
app$setInputs(Res_strategy = "cv")
app$snapshot()
app$setInputs(navbar = "5. Benchmarking")
app$setInputs(Bench_learners = "Learner1")
app$setInputs(Bench_learners = c("Learner1", "Learner2"))
app$setInputs(Bench_start = "click")
app$setInputs(Bench_ratio = 0)
app$setInputs(Bench_ratio = 0.7)
app$snapshot()
app$setInputs(navbar = "6. Predict")
app$setInputs(Pred_learner = "Learner1")
app$snapshot()
