app <- ShinyDriver$new("../", seed = 42, loadTimeout = 1e+05, shinyOptions = list(port = 8000))
app$snapshotInit("workflow_test_without_DT")

app$snapshot()
app$setInputs(navbar = "3. Learner")
app$setInputs(Learner_Create1 = "click")
app$setInputs(Learner_add = "click")
app$setInputs(Learner_Learner2 = "classif.ranger")
app$setInputs(Learner_Create2 = "click")
app$setInputs(Learner2Parammtry = 2)
app$setInputs(Learner2ChangeParams = "click")
app$setInputs(Learner2PredictTypeChoice = "prob")
app$setInputs(Learner2PredictTypeChange = "click")
app$snapshot()
app$setInputs(navbar = "4. Train & Evaluate")
app$setInputs(TrainFit_resample = "click")
app$snapshot()
app$setInputs(navbar = "5. Benchmarking")
app$setInputs(Bench_learners = "Learner1")
app$setInputs(Bench_learners = c("Learner1", "Learner2"))
app$setInputs(Bench_res_strategy = "cv")
app$setInputs(Bench_start = "click")
app$setInputs(Bench_benchmark = "click")
app$snapshot()
app$setInputs(navbar = "6. Predict")
app$setInputs(Pred_learner = "Learner1")
app$setInputs(Pred_train_learner = "click")
app$snapshot()
